[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
prediction = "Bki3CWk4AmVF78zvh81rup2EK2iJY4WRCUXesAv8TECF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./prediction.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]] # switchboard-solana devnet programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # switchboard-solana devnet IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # switchboard-solana SOL/USD Feed
address = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"