[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
prediction = "FW9KvGkRcnibqm5LSE4J8sq3homgVizKGBoNA511gR2s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./prediction.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
